export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_ROUTE = '/home'
export const ABOUT_ROUTE = '/about'
export const BOOK_ROUTE = '/book'
export const CATALOG_ROUTE = '/catalog'
